apiVersion: v1
kind: Template
metadata:
  name: init-job-buildconfig
  annotations:
    description: >
      This is Thoth Init Job BuildConfig, this template is meant to be used by
      Bots, but could also be used by humans...
    openshift.io/display-name: 'Thoth Core: Init Job BuildConfig'
    version: 0.1.0
    tags: thoth,thoth-init-job,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Thoth Init Job BuildConfig, this template is meant to be used
      by Bots, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.1.0
  labels:
    template: init-job-buildconfig
    app: thoth
    component: init-job

objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: init-job
      annotations:
        thoth-station.ninja/template-version: 0.1.0
      labels:
        app: thoth
        component: init-job
    spec:
      successfulBuildsHistoryLimit: 1
      failedBuildsHistoryLimit: 2
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 512Mi
      output:
        to:
          kind: ImageStreamTag
          name: "init-job:${IMAGE_STREAM_TAG}"
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: s2i-thoth-ubi8-py36:latest
          env:
            - name: ENABLE_PIPENV
              value: '1'
            - name: UPGRADE_PIP_TO_LATEST
              value: ''
            - name: "THOTH_DRY_RUN"
              value: "1"
            - name: "THOTH_ADVISE"
              value: ${THOTH_ADVISE}
            - name: "THOTH_PROVENANCE_CHECK"
              value: ${THOTH_PROVENANCE_CHECK}
            - name: "THAMOS_VERBOSE"
              value: "1"
            - name: "THAMOS_DEBUG"
              value: "0"
            - name: "THAMOS_CONFIG_TEMPLATE"
              value: ".thoth.yaml"
            - name: "THAMOS_CONFIG_EXPAND_ENV"
              value: "1"
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: Generic
          generic:
            secretReference:
              name: generic-webhook-secret

parameters:
  - description: Name of the github repository for Thoth's Init Job
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/init-job'

  - description: Git reference to be used for Thoth's Init Job
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: >
      Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'

  - description: Thamos Advise setup tag value
    displayName: THOTH_ADVISE
    required: true
    name: THOTH_ADVISE
    value: "0"

  - description: Thamos Provenance Check setup tag flag
    displayName: THOTH_PROVENANCE_CHECK
    required: false
    name: THOTH_PROVENANCE_CHECK
    value: "0"
